export const siteConfig = {
  url: 'https://www.michaelzick.com',
  name: 'Michael Zick | Reality Alignment Coach',
  shortName: 'Michael Zick',
  description: 'Helping high-functioning adults separate fear and anxiety from reality.',
  businessName: 'Michael Zick Coaching',
  locale: 'en_US',
  placename: 'Los Angeles',
  region: 'US-CA',
  defaultImage: '/img/homepage_mountains.webp',
  personImage: '/img/grey-suit-blue-shirt.webp',
  keywords: [
    'Reality Alignment Coach',
    'Life coaching',
    'Life coach',
    'High-functioning adults',
    'Somatic regulation',
    'Relationship coaching',
    'Relationship coach',
    'No More Mr. Nice Guy',
    'NMMNG',
    'Nice Guy Syndrome',
    'Nice Guys No More',
    'Los Angeles',
  ],
  sameAs: ['https://michaelzick.medium.com'],
} as const;
