export const siteConfig = {
  url: 'https://www.michaelzick.com',
  name: 'Michael Zick | Nice Guy Recovery Coach',
  shortName: 'Michael Zick',
  description: 'Michael Zick is an LA-based Nice Guy Recovery Coach helping high-functioning men break free from approval addiction, toxic shame, and enmeshment to reclaim internal authority.',
  businessName: 'Michael Zick Coaching',
  locale: 'en_US',
  placename: 'Los Angeles',
  region: 'US-CA',
  defaultImage: '/img/homepage_mountains.webp',
  personImage: '/img/grey-suit-blue-shirt.webp',
  keywords: [
    'Nice Guy Recovery Coach',
    'Approval Addiction',
    'Internal Authority',
    'Self-Led Masculinity',
    'Reality Alignment Coach',
    'LA life coach',
    'life coach in LA',
    'men\'s coach',
    'No More Mr. Nice Guy',
    'NMMNG',
    'Nice Guy Syndrome',
    'Nice Guys No More',
    'Los Angeles life coach',
    'Relationship coaching',
    'Somatic regulation',
  ],
  sameAs: [
    'https://michaelzick.medium.com',
    'https://www.linkedin.com/in/michaelzick',
    'https://www.zickonezero.com',
  ]
} as const;
