import type { Metadata } from 'next';
import Link from 'next/link';
import { siteConfig } from '../../lib/site';

export const metadata: Metadata = {
  title: 'Terms of Service | Michael Zick Coaching',
  description: 'The terms that govern your use of michaelzick.com, including coaching disclaimers, the AI questionnaire, and third-party services.',
  alternates: {
    canonical: '/terms-of-service',
  },
  openGraph: {
    title: 'Terms of Service | Michael Zick Coaching',
    description: 'The terms that govern your use of michaelzick.com, including coaching disclaimers, the AI questionnaire, and third-party services.',
    url: `${siteConfig.url}/terms-of-service`,
    siteName: siteConfig.name,
    type: 'website',
    locale: siteConfig.locale,
  },
};

const sectionHeading = 'font-headline text-3xl font-semibold leading-tight';
const body = 'text-lg';
const list = 'list-disc pl-6 space-y-2 text-lg';
const inlineLink = 'underline underline-offset-4 transition hover:text-primary-blue';

export default function TermsOfService() {
  return (
    <div className="flex flex-col">
      <section className="page-top-offset px-6 pb-24 md:px-8 md:pb-32 bg-light-grey text-default-grey">
        <div className="mx-auto max-w-[900px] space-y-12">
          <div className="space-y-6">
            <h1 className="font-headline text-5xl font-semibold leading-tight md:text-6xl">
              Terms of Service
            </h1>
            <p className="text-lg">
              <strong>Effective Date:</strong> August 11, 2026
            </p>
            <p className={body}>
              Welcome. These Terms of Service (&quot;Terms&quot;) govern your use of
              michaelzick.com, the website of Michael Zick Coaching. By using this site, you agree
              to these Terms.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className={sectionHeading}>1. What This Site Is</h2>
            <p className={body}>
              michaelzick.com shares Nice Guy Recovery coaching content — articles, testimonials,
              and course information — and offers tools to connect with Michael: a contact form, a
              coaching questionnaire with an AI-generated analysis, a Nice Guy University coupon
              signup, and links to schedule sessions. The site has no user accounts and processes
              no payments.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className={sectionHeading}>2. Coaching Is Not Therapy</h2>
            <p className={body}>
              Coaching, and everything published on this site, is educational and informational.
              It is not psychotherapy, counseling, medical care, or mental-health treatment, and
              it is not a substitute for any of those. Working with a coach does not create a
              therapist–patient or doctor–patient relationship. If you are in crisis or think you
              may harm yourself or someone else, contact your local emergency number or a crisis
              line immediately.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className={sectionHeading}>3. The Questionnaire and AI-Generated Content</h2>
            <p className={body}>
              The questionnaire&apos;s coaching analysis is generated by an AI model from the
              answers you provide. It is a starting point for reflection, not a diagnosis or
              professional assessment. AI-generated content can be imperfect or incomplete;
              decisions about your life, health, or relationships remain yours.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className={sectionHeading}>4. Acceptable Use</h2>
            <p className={body}>You agree not to:</p>
            <ul className={list}>
              <li>Use the site for any unlawful purpose.</li>
              <li>Submit false, abusive, or malicious content through the forms.</li>
              <li>Bypass security or spam protections, or disrupt the site&apos;s operation.</li>
              <li>Scrape, harvest, or republish site content without permission.</li>
            </ul>
          </div>

          <div className="space-y-4">
            <h2 className={sectionHeading}>5. Sessions, Courses, and Third-Party Services</h2>
            <p className={body}>
              Booking a session happens through Calendly, and Nice Guy University courses are
              purchased and taken on their own platform — each is governed by its own terms and
              policies. Coaching engagements themselves are agreed separately between you and
              Michael Zick Coaching. Links to third-party sites are provided for convenience; we
              don&apos;t control them and aren&apos;t responsible for their content.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className={sectionHeading}>6. Intellectual Property</h2>
            <p className={body}>
              The site&apos;s content — writing, blog posts, images, and design — belongs to
              Michael Zick Coaching or its licensors. You may read and share links freely; you may
              not reproduce or commercially exploit the content without written permission.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className={sectionHeading}>7. Privacy</h2>
            <p className={body}>
              Our <Link href="/privacy-policy" className={inlineLink}>Privacy Policy</Link>{' '}
              explains what we collect and how it&apos;s used, including analytics and session
              replay. You can manage analytics cookies anytime via the cookie consent banner or
              the Cookie Preferences link in the footer.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className={sectionHeading}>8. Disclaimers</h2>
            <p className={body}>
              The site is provided &quot;as is&quot; and &quot;as available,&quot; without
              warranties of any kind, express or implied. We don&apos;t warrant that the site will
              be uninterrupted, error-free, or that results described in testimonials or content
              will apply to you — outcomes depend on your own effort and circumstances.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className={sectionHeading}>9. Limitation of Liability</h2>
            <p className={body}>
              To the fullest extent permitted by law, Michael Zick Coaching shall not be liable
              for any indirect, incidental, special, consequential, or punitive damages arising
              from your use of the site or its content.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className={sectionHeading}>10. Changes to These Terms</h2>
            <p className={body}>
              We may update these Terms from time to time. Changes will be posted on this page
              with an updated effective date, and continued use of the site constitutes
              acceptance.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className={sectionHeading}>11. Governing Law</h2>
            <p className={body}>
              These Terms are governed by the laws of the State of California, without regard to
              conflict of law principles.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className={sectionHeading}>12. Contact</h2>
            <p className={body}>
              Questions about these Terms? Reach out through the{' '}
              <Link href="/contact" className={inlineLink}>contact page</Link>.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}
